apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-publisher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pubsub-publisher
  template:
    metadata:
      labels:
        app: pubsub-publisher
    spec:
      containers:
       - name: pubsub-publisher
         image: pubsub-publisher:latest
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /app/data-pipleine-keys.json
            volumeMounts:
          - mountPath: /app
            name: gcp-credentials
            volumes:
          - name: gcp-credentials
            secret:
            secretName: gcp-keyfile
---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-keyfile
type: Opaque
data:
  data-pipleine-keys.json: <base64-encoded-gcp-keyfile>
